version: "3.8"
services:
  mysqldb:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_DATABASE=capstone_pod
    ports:
      - 3307:3306
    networks:
      - app_network
  app:
    depends_on:
      - mysqldb
    build:
      context: "./"
    ports:
      - 8080:8080
    networks:
      - app_network
networks:
  app_network:
    driver: bridge