version: "3.4"
services:
  mysqldb:
    image: mysql:8.0.29
    container_name: mysqldb
    environment:
        MYSQL_DATABASE: capstone_pod
        MYSQL_ROOT_PASSWORD: 123456789
    restart: unless-stopped
    networks:
      - app_network
    volumes:
      - db_data:/var/lib/mysql
  spring-app:
    depends_on:
      - mysqldb
    environment:
          SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/capstone_pod?allowPublicKeyRetrieval=true&useSSL=false
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: 123456789
    build:
      context: ./
    ports:
      - '8080:8080'
    networks:
      - app_network
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9000:80
    environment:
      - PMA_HOST=mysqldb
      - PMA_USER=root
      - PMA_PASSWORD=123456789
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
volumes:
  db_data: